# Generates thunks.h from cfgmgr32.spec (Wine's export list for cfgmgr32.dll): one pass-through
# for every exported function, calling the same function in Windows' own cfgmgr32.dll. The few
# functions the shim overrides are listed in OVERRIDES and skipped here.
import re, sys
OVERRIDES = {"CM_Get_Parent", "CM_Get_Parent_Ex", "CM_Get_DevNode_PropertyW", "CM_Get_DevNode_Property_ExW"}
SIZE = {"ptr": "ULONG_PTR", "long": "ULONG_PTR", "wstr": "ULONG_PTR", "str": "ULONG_PTR", "int64": "ULONGLONG", "long64": "ULONGLONG", "double": "double", "float": "float"}
out = ["/* generated by gen.py from cfgmgr32.spec — do not edit */"]
names = []
for line in open(sys.argv[1]):
    m = re.match(r"@\s+stdcall\s+(\w+)\s*\(([^)]*)\)\s*(\S*)", line)
    if not m: continue
    name, args, forward = m.groups()
    if name in OVERRIDES: continue
    types = [SIZE[a] for a in args.split()]
    params = ", ".join(f"{t} a{i}" for i, t in enumerate(types)) or "void"
    call = ", ".join(f"a{i}" for i in range(len(types)))
    out.append(f"typedef ULONG_PTR (WINAPI *fn_{name})({params});")
    out.append(f"ULONG_PTR WINAPI {name}({params}) {{ static fn_{name} f; if (!f) f = (fn_{name})shim_real(\"{name}\"); return f ? f({call}) : CR_CALL_NOT_IMPLEMENTED; }}")
    names.append(name)
open("thunks.h", "w").write("\n".join(out) + "\n")
open("exports.def", "w").write("EXPORTS\n" + "\n".join(sorted(names | OVERRIDES if False else names + sorted(OVERRIDES))) + "\n")
print(len(names), "thunks")
